included:
  - Package.swift
  - Example
  - MultipleImageView
opt_in_rules:
  - contains_over_first_not_nil
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - extension_access_modifier
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - nimble_operator
  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
disabled_rules:
  - nesting
  - function_parameter_count
  - cyclomatic_complexity
  - large_tuple
line_length: 130
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 100
  error: 200