name: Swift build

on: push

jobs:
  build:
     runs-on: macos-latest

     steps:
     - uses: actions/checkout@v4

     - name: Build
       run: swift build -Xswiftc -sdk -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" -Xswiftc -target -Xswiftc x86_64-apple-ios13.0-simulator
